env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  class-methods-use-this: off
  no-await-in-loop: off
  no-use-before-define: off
  import/no-unresolved: "off"
  import/extensions: "off"
