name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: typescript build
        run: |
          CI_COMMIT_TAG=${GITHUB_REF##*/}
          npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
          npm install
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
      - name: save source
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dict
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: load source
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: publish
        run: npm publish
